services:
  email-processor:
    build: .
    container_name: email-processor
    restart: unless-stopped
    volumes:
      # Для сохранения сессии Telegram между перезапусками
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
